name: Build masscan for Windows

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Build masscan
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          nmake -f Makefile.msvc all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: masscan-win64
          path: bin\masscan.exe
